### ISSUE TITLE
unpack requires a buffer of 4 bytes

### ISSUE THREAD

**Issue by dekiel123** [Nineteendo/PVZ2tools#17]
```
error while extracting C:\Users\User\Desktop\dddd\PVZ2tools-beta\OBBEdit\main.483.com.ea.game.pvz2_roE.obb:Packages: unpack requires a buffer of 4 bytes
Traceback (most recent call last):
  File "C:\Users\User\Desktop\dddd\PVZ2tools-beta\OBBEdit\unpack.py", line 247, in rsg_extract
    IMAGE_DATA_OFFSET = unpack("<I", file.read(4))[0]
struct.error: unpack requires a buffer of 4 bytes

```

Any idea what to do?

**Comment by Nineteendo** [comment]
Can you send that obb, it appears that something is wrong with it.
It tries to read from an empty subfile...

**Comment by dekiel123** [comment]
https://drive.google.com/file/d/116_ie7IY_b1weguPvfXX1egJ5ATU-PYK/view?usp=sharing

I need all files from "PACKAGES" in this obb, can you help me get this?

**Comment by Nineteendo** [comment]
I'll try when you've given me access to the file.
I can't promise anything, some mods just don't want to be messed with.

**Comment by Nineteendo** [comment]
<img width="2048" alt="Screenshot 2022-07-28 at 14 44 02" src="https://user-images.githubusercontent.com/65588599/181507973-dce74316-59d1-4815-bd91-bbc109ff2000.png">

**Comment by dekiel123** [comment]
Done, try now.

**Comment by Nineteendo** [comment]
See, the size in column 5 is set to 0. I'm going to check if I'm using a work-around already.
<img width="2048" alt="Screenshot 2022-07-28 at 14 55 59" src="https://user-images.githubusercontent.com/65588599/181510389-b2d29c1e-c5e9-4f34-abb8-a38ab1c37ce0.png">

**Comment by Nineteendo** [comment]
OK, they've just bypassed my work-around:
`RSG_SIZE = RSG_IMAGE_DATA_OFFSET + RSG_COMPRESSED_IMAGE_DATA_SIZE`
Both are set to zero in their file (column 12 and 13 respectively)
So it becomes this:
`RSG_SIZE = max(RSG_DATA_OFFSET + RSG_COMPRESSED_DATA_SIZE, RSG_IMAGE_DATA_OFFSET + RSG_COMPRESSED_IMAGE_DATA_SIZE)`
Which version are you currently using?

**Comment by Nineteendo** [comment]
This is what I currently have extracted:
[main.483.com.ea.game.pvz2_roE.obb.zip](https://github.com/Nineteendo/PVZ2tools/files/9209856/main.483.com.ea.game.pvz2_roE.obb.zip)

**Comment by Nineteendo** [comment]
OK, that's also tackled, that just leaves this one file:
![Screenshot 2022-07-28 at 15 10 21](https://user-images.githubusercontent.com/65588599/181513167-5fb6a5a2-8a30-47cf-a992-255e5a9a32f1.png)
I have no idea what \x83\x84 is supposed to mean.

**Comment by dekiel123** [comment]
> This is what I currently have extracted: [main.483.com.ea.game.pvz2_roE.obb.zip](https://github.com/Nineteendo/PVZ2tools/files/9209856/main.483.com.ea.game.pvz2_roE.obb.zip)

Thank you so much! That will help me a lot :)

**Comment by Nineteendo** [comment]
Here's the almost complete archive:
[main.483.com.ea.game.pvz2_roE.obb.zip](https://github.com/Nineteendo/PVZ2tools/files/9209939/main.483.com.ea.game.pvz2_roE.obb.zip)
In the next beta the problem will be resolved.

**Comment by Nineteendo** [comment]
What even is this?
![Screenshot 2022-07-28 at 15 18 31](https://user-images.githubusercontent.com/65588599/181514865-73b2be6f-d673-4e9b-8aa4-3e2070ce61b8.png)

**Comment by dekiel123** [comment]
> OK, they've just bypassed my work-around: `RSG_SIZE = RSG_IMAGE_DATA_OFFSET + RSG_COMPRESSED_IMAGE_DATA_SIZE` Both are set to zero in their file (column 12 and 13 respectively) So it becomes this: `RSG_SIZE = max(RSG_DATA_OFFSET + RSG_COMPRESSED_DATA_SIZE, RSG_IMAGE_DATA_OFFSET + RSG_COMPRESSED_IMAGE_DATA_SIZE)` Which version are you currently using?

Beta version.

.....
May i ask you once again for help with other OBB? There is exacly the same problem "unpack requires a buffer of 4 bytes".
https://drive.google.com/file/d/1-uDaPaaOUOgyQrhGz_8jARkKS98F_uxL/view?usp=sharing

**Comment by Nineteendo** [comment]
[main.18.com.ea.game.pvz2_shu.obb.zip](https://github.com/Nineteendo/PVZ2tools/files/9211630/main.18.com.ea.game.pvz2_shu.obb.zip)

**Comment by Nineteendo** [comment]
You can use the latest version of the beta, but be quick before I break the script again: https://github.com/Nineteendo/PVZ2tools/tree/beta

**Comment by dekiel123** [comment]
Thank you :)

**Comment by dekiel123** [comment]
After the latest update, problem returned:

error while extracting G:\PVZ2tools-beta\Shuttle 1\main.18.com.ea.game.pvz2_shu.obb:__BuildOn971ByCz__: unpack requires a buffer of 4 bytes
Traceback (most recent call last):
  File "G:\PVZ2tools-beta\unpack.py", line 246, in rsg_extract
    IMAGE_DATA_OFFSET = unpack("<I", file.read(4))[0]
struct.error: unpack requires a buffer of 4 bytes

**Comment by Nineteendo** [comment]
> After the latest update, problem returned:
> 
> ```
> error while extracting G:\PVZ2tools-beta\Shuttle 1\main.18.com.ea.game.pvz2_shu.obb:__BuildOn971ByCz__: unpack requires a buffer of 4 bytes
> Traceback (most recent call last):
>   File "G:\PVZ2tools-beta\unpack.py", line 246, in rsg_extract
>     IMAGE_DATA_OFFSET = unpack("<I", file.read(4))[0]
> struct.error: unpack requires a buffer of 4 bytes
> ```
I'll check & compare with the previous version. Did the obb update?

**Comment by Nineteendo** [comment]
<img width="1259" alt="Screenshot 2022-09-08 at 14 03 46" src="https://user-images.githubusercontent.com/65588599/189117238-d55988a3-a402-4304-98a5-f0afef0b2902.png">
Can you share me the latest version? It works fine for the previous version I downloaded.

**Comment by dekiel123** [comment]
Yes there was a new update.
https://drive.google.com/file/d/1v42Yl0nxb42z2ok24jno-q35olc45iHY/view?usp=sharing

**Comment by Nineteendo** [comment]
Are you using the latest version of PyVZ2? https://github.com/Nineteendo/PVZ2tools
If that still fails you can use this: https://cdn.discordapp.com/attachments/942096976718204929/1013320454422941797/Pyvz2_alpha_1.2.2c.zip
