### ISSUE TITLE
Patching Error

### ISSUE THREAD

**Issue by Kskskdkzkaiao** [Nineteendo/PVZ2tools#60]
Hello! I tried patching Heaven OBB but it gave me the following error:
Download new update: https://github.com/Nineteendo/PVZ2tools/tree/beta
Failed OBBPatch: ValidationError: in /storage/emulated/0/Android/obb/com.ea.game.pvz2_row (1)/main.790.com.ea.game.pvz2_row.obb RSG_SIZE is incorrect: 6103040 != 6101612
Traceback (most recent call last):
  File "<string>", line 428, in file_to_folder
  File "<string>", line 386, in archive_patch
  File "<string>", line 324, in rsb_patch_data
libraries.pyvz2.constants.ValidationError: RSG_SIZE is incorrect: 6103040 != 6101612

The unpacking works but the patching doesn't

**Comment by Kskskdkzkaiao** [comment]
Nvm, i was using alpha version
After trying it with beta version it worked!
